---
title: "Distribution des contextes des phonemes"
output: html_document
---

```{r setup, include=FALSE}
library(plyr)
library(ggplot2)

dist <- read.csv("data/data_cleaned/GetStat.csv", header=F)
names(dist) <- c("context", "phoneme", "count")

```

## Probability of most probable phoneme by context

```{r prob}
mean_count <- function(d) {
  m <- mean(d$count)
  result <- data.frame(mean_count=m)
  return(result)
}
prob_max <- function(x) {
  return(max(x)/sum(x))
}

phone_max <- function(x,y) {
  return(x[which.max(y)])
} 

prob <- ddply(dist, .(context), summarize, mean_count=mean(count))
prob <- ddply(dist, .(context), mean_count)

prob <- ddply(dist, .(context), summarize,
              prob_max=prob_max(count),
              phone_max=phone_max(phoneme, count),
              prob_context=sum(count)/sum(dist$count))
prob$weighted_error <- (1-prob$prob_max)*prob$prob_context/sum(prob$prob_max*prob$prob_context)
new_levels <- prob$context[order(prob$weighted_error, decreasing = T)]
prob$context <- factor(prob$context, levels=new_levels)
ggplot(prob[prob$weighted_error>0.0030,], aes(x=context, y=weighted_error)) + geom_point()  + theme(axis.text.x = element_text(angle = 90))



sprintf("stat. error rate = %s", sum((1-prob$prob_max)*prob$prob_context))
```

